
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/supabase';

// Instead of creating a new client, let's export the one from lib/supabase.ts
export { supabase } from '@/lib/supabase';
